### ISSUE TITLE
The file of modeling_options.yaml and analysis_options.yaml

### ISSUE THREAD

**Issue by Stephen-cby** [IEAWindTask37/IEA-22-280-RWT#19]
Hi, everyone.

I copied modeling_options.yaml and analysis_options.yaml from IEA-15-240-RWT. I tried to run `wisdem` for IEA-22-280-RWT. An error occurred as listed.

Traceback (most recent call last):
  File "G:\15MW\OpenFAST3.5.0\IEA-15-240-RWT-1.1.6\IEA-22-280-RWT-main\WISDEM\TestIEA-Driver001.py", line 31, in <module>
    wt_opt, analysis_options, opt_options = run_wisdem(fname_wt_input, fname_modeling_options, fname_analysis_options)
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Anaconda3\all\envs\wisdem-env\Lib\site-packages\wisdem\glue_code\runWISDEM.py", line 125, in run_wisdem
    wt_opt = yaml2openmdao(wt_opt, modeling_options, wt_init, opt_options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Anaconda3\all\envs\wisdem-env\Lib\site-packages\wisdem\glue_code\gc_WT_InitModel.py", line 40, in yaml2openmdao
    wt_opt = assign_airfoil_values(wt_opt, modeling_options, airfoils)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Anaconda3\all\envs\wisdem-env\Lib\site-packages\wisdem\glue_code\gc_WT_InitModel.py", line 1421, in assign_airfoil_values
    cl[i, :, j_Re[j], k] = PchipInterpolator(
                           ^^^^^^^^^^^^^^^^^^
  File "G:\Anaconda3\all\envs\wisdem-env\Lib\site-packages\scipy\interpolate\_cubic.py", line 234, in __init__
    x, _, y, axis, _ = prepare_input(x, y, axis)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Anaconda3\all\envs\wisdem-env\Lib\site-packages\scipy\interpolate\_cubic.py", line 48, in prepare_input
    raise ValueError("The length of `y` along `axis`={0} doesn't "
ValueError: The length of `y` along `axis`=0 doesn't match the length of `x`

Could anyone please provide the right file of modeling_options.yaml and analysis_options.yaml for IEA-22-280-RWT? Thanks a lot.

**Comment by Stephen-cby** [comment]
Dear @fzahle,

I appreciate your reply sincerely.

It would be better if you can share the right geometry file of IEA-22-280-RWT. Since I tried to manually modify the original file, another error still occurs.

**Comment by fzahle** [comment]
We would like to keep the three airfoil polars options in there, since these are needed for comparison to higher fidelity  aerodynamics codes, so if that didn't fix it for you I'm afraid I can't help much more. I know @ptrbortolotti has run it through WISDEM, so he can probably assist you with either a code fix in WISDEM or needed changes in the yaml.

**Comment by ptrbortolotti** [comment]
Hello,
fzahle is right, WISDEM doesn't know what set of polars to load from the yaml because they all have the same Re number, and it errors out. 
If you comment out the extra polar sets, WISDEM runs.
Try running the files below, they should work
[issue19_iea22.zip](https://github.com/IEAWindTask37/IEA-22-280-RWT/files/12153072/issue19_iea22.zip)

**Comment by Stephen-cby** [comment]
Hi @ptrbortolotti and @fzahle.

A million thanks to you. The files shared by you can be run by WISDEM. I appreciate your help, again.

It would be so kind if you can continue to answer my question. Whether the configuration of IEA-22-280 is optimized. WISDEM has the function of optimization, like towards the whole turbine or tower and monopile.

**Comment by ptrbortolotti** [comment]
The tower and monopile of the IEA22 have been optimized to meet frequency, stresses, and buckling constraints. In addition, the diameter to thickness ratio is constrained between 90 and 150. Does this answer your question?
I am not sure what you mean with "running time". In WISDEM? Or in OpenFAST?

**Comment by Stephen-cby** [comment]
Hi, @ptrbortolotti.

Thanks for your help. I understand that IEA22 has been optimized.

I mean the run time in WISDEM. The time when I run IEA22 in WISDEM is about 33 seconds, while the run time of IEA15 is about 150 seconds. I am just curious about the difference.

**Comment by ptrbortolotti** [comment]
Hello Sangwon,
the model has now settled. Is this still an active issue?
Best regards

**Comment by wonny0503** [comment]
Dear @ptrbortolotti 

I confirmed steady-state analysis is normal.

I really appreciate your and other members efforts to develop this model.

Best regards,
Sangwon
